// This file will be auto-generated by: supabase gen types typescript
// For now, provide a placeholder that matches our schema

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          avatar_url: string | null;
          phone: string | null;
          paypal_email: string | null;
          email: string | null;
          is_placeholder: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          first_name: string;
          last_name: string;
          avatar_url?: string | null;
          phone?: string | null;
          paypal_email?: string | null;
          email?: string | null;
          is_placeholder?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_name?: string;
          last_name?: string;
          avatar_url?: string | null;
          phone?: string | null;
          paypal_email?: string | null;
          email?: string | null;
          is_placeholder?: boolean;
          updated_at?: string;
        };
      };
      clubs: {
        Row: {
          id: string;
          name: string;
          logo_url: string | null;
          contact_email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          logo_url?: string | null;
          contact_email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          logo_url?: string | null;
          contact_email?: string | null;
          updated_at?: string;
        };
      };
      club_members: {
        Row: {
          id: string;
          club_id: string;
          user_id: string;
          status: 'active' | 'inactive';
          join_date: string;
          player_type: 'batter' | 'bowler' | 'all_rounder' | null;
          batting_hand: 'left' | 'right' | null;
          bowling_type: 'offspin' | 'legspin' | 'pace' | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          club_id: string;
          user_id: string;
          status?: 'active' | 'inactive';
          join_date?: string;
          player_type?: 'batter' | 'bowler' | 'all_rounder' | null;
          batting_hand?: 'left' | 'right' | null;
          bowling_type?: 'offspin' | 'legspin' | 'pace' | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          status?: 'active' | 'inactive';
          join_date?: string;
          player_type?: 'batter' | 'bowler' | 'all_rounder' | null;
          batting_hand?: 'left' | 'right' | null;
          bowling_type?: 'offspin' | 'legspin' | 'pace' | null;
          notes?: string | null;
        };
      };
      club_member_roles: {
        Row: {
          id: string;
          member_id: string;
          role: 'admin' | 'captain' | 'player';
          created_at: string;
        };
        Insert: {
          id?: string;
          member_id: string;
          role: 'admin' | 'captain' | 'player';
          created_at?: string;
        };
        Update: {
          role?: 'admin' | 'captain' | 'player';
        };
      };
      years: {
        Row: {
          id: string;
          club_id: string;
          year: number;
          label: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          club_id: string;
          year: number;
          label?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          year?: number;
          label?: string | null;
          is_active?: boolean;
        };
      };
      teams: {
        Row: {
          id: string;
          club_id: string;
          year_id: string;
          name: string;
          description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          club_id: string;
          year_id: string;
          name: string;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          updated_at?: string;
        };
      };
      team_members: {
        Row: {
          id: string;
          team_id: string;
          user_id: string;
          is_captain: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          team_id: string;
          user_id: string;
          is_captain?: boolean;
          created_at?: string;
        };
        Update: {
          is_captain?: boolean;
        };
      };
      games: {
        Row: {
          id: string;
          team_id: string;
          opponent: string;
          location: string | null;
          game_date: string;
          game_time: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          team_id: string;
          opponent: string;
          location?: string | null;
          game_date: string;
          game_time?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          opponent?: string;
          location?: string | null;
          game_date?: string;
          game_time?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
      };
      game_selections: {
        Row: {
          id: string;
          game_id: string;
          user_id: string;
          batting_order: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          user_id: string;
          batting_order?: number | null;
          created_at?: string;
        };
        Update: {
          batting_order?: number | null;
        };
      };
      expenses: {
        Row: {
          id: string;
          club_id: string;
          year_id: string | null;
          team_id: string | null;
          game_id: string | null;
          description: string;
          amount_cents: number;
          category: 'ground_booking' | 'equipment' | 'travel' | 'food' | 'umpire' | 'registration' | 'kit' | 'other';
          expense_date: string;
          created_by: string | null;
          paid_by_user_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          club_id: string;
          year_id?: string | null;
          team_id?: string | null;
          game_id?: string | null;
          description: string;
          amount_cents: number;
          category?: 'ground_booking' | 'equipment' | 'travel' | 'food' | 'umpire' | 'registration' | 'kit' | 'other';
          expense_date?: string;
          created_by?: string | null;
          paid_by_user_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          year_id?: string | null;
          team_id?: string | null;
          game_id?: string | null;
          description?: string;
          amount_cents?: number;
          category?: 'ground_booking' | 'equipment' | 'travel' | 'food' | 'umpire' | 'registration' | 'kit' | 'other';
          expense_date?: string;
          paid_by_user_id?: string | null;
          updated_at?: string;
        };
      };
      expense_assignments: {
        Row: {
          id: string;
          expense_id: string;
          user_id: string;
          share_cents: number;
          status: 'pending' | 'paid' | 'cancelled';
          paid_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          expense_id: string;
          user_id: string;
          share_cents: number;
          status?: 'pending' | 'paid' | 'cancelled';
          paid_at?: string | null;
          created_at?: string;
        };
        Update: {
          share_cents?: number;
          status?: 'pending' | 'paid' | 'cancelled';
          paid_at?: string | null;
        };
      };
      payments: {
        Row: {
          id: string;
          club_id: string;
          year_id: string | null;
          title: string;
          description: string | null;
          amount_cents: number;
          due_date: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          club_id: string;
          year_id?: string | null;
          title: string;
          description?: string | null;
          amount_cents: number;
          due_date?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          year_id?: string | null;
          title?: string;
          description?: string | null;
          amount_cents?: number;
          due_date?: string | null;
          updated_at?: string;
        };
      };
      payment_assignments: {
        Row: {
          id: string;
          payment_id: string;
          user_id: string;
          status: 'pending' | 'paid' | 'cancelled';
          paid_at: string | null;
          paypal_order_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          payment_id: string;
          user_id: string;
          status?: 'pending' | 'paid' | 'cancelled';
          paid_at?: string | null;
          paypal_order_id?: string | null;
          created_at?: string;
        };
        Update: {
          status?: 'pending' | 'paid' | 'cancelled';
          paid_at?: string | null;
          paypal_order_id?: string | null;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
